name: Build for Non-Main Branches

on:
  push:
    branches-ignore:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build-unix-time: ${{ steps.variable.outputs.build_unix_time }}
      build-date: ${{ steps.variable.outputs.build_date }}
      docker-tags: ${{ steps.meta.outputs.tags }}
      docker-labels: ${{ steps.meta.outputs.labels }}
      ezbookkeeping-docker-bake-meta-file-path: ${{ steps.variable.outputs.ezbookkeeping_docker_bake_meta_file_path }}
      ezbookkeeping-docker-bake-meta-artifact-name: ${{ steps.variable.outputs.ezbookkeeping_docker_bake_meta_artifact_name }}
      ezbookkeeping-docker-digests-file-path: ${{ steps.variable.outputs.ezbookkeeping_docker_digests_file_path }}
      ezbookkeeping-docker-digests-artifact-name-prefix: ${{ steps.variable.outputs.ezbookkeeping_docker_digests_artifact_name_prefix }}
      ezbookkeeping-package-file-name-prefix: ${{ steps.variable.outputs.ezbookkeeping_package_file_name_prefix }}
      ezbookkeeping-package-artifact-name-prefix: ${{ steps.variable.outputs.ezbookkeeping_package_artifact_name_prefix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=dev-${{ github.run_id }}

      - name: Set up variables
        id: variable
        run: |
          echo "build_unix_time=$(date '+%s')" >> "$GITHUB_OUTPUT"
          echo "build_date=$(date '+%Y%m%d')" >> "$GITHUB_OUTPUT"
          echo "ezbookkeeping_docker_bake_meta_file_path=${{ runner.temp }}/bake-meta.json" >> "$GITHUB_OUTPUT"
          echo "ezbookkeeping_docker_bake_meta_artifact_name=ezbookkeeping-build-dev-docker-bake-meta-${{ github.run_id }}" >> "$GITHUB_OUTPUT"
          echo "ezbookkeeping_docker_digests_file_path=${{ runner.temp }}/digests" >> "$GITHUB_OUTPUT"
          echo "ezbookkeeping_docker_digests_artifact_name_prefix=ezbookkeeping-build-dev-digests-${{ github.run_id }}" >> "$GITHUB_OUTPUT"
          echo "ezbookkeeping_package_file_name_prefix=ezbookkeeping-dev-package-${{ github.run_id }}" >> "$GITHUB_OUTPUT"
          echo "ezbookkeeping_package_artifact_name_prefix=ezbookkeeping-build-dev-package-${{ github.run_id }}" >> "$GITHUB_OUTPUT"

      - name: Rename docker bake meta file
        run: |
          mv "${{ steps.meta.outputs.bake-file }}" "${{ steps.variable.outputs.ezbookkeeping_docker_bake_meta_file_path }}"

      - name: Upload docker bake meta artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.variable.outputs.ezbookkeeping_docker_bake_meta_artifact_name }}
          path: ${{ steps.variable.outputs.ezbookkeeping_docker_bake_meta_file_path }}
          if-no-files-found: error

  build-linux-docker-and-package-x86:
    runs-on: ubuntu-24.04
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: ./.github/actions/build-linux-docker-and-package
        with:
          build-unix-time: ${{ needs.setup.outputs.build-unix-time }}
          build-date: ${{ needs.setup.outputs.build-date }}
          check-3rd-api: ${{ vars.CHECK_3RD_API }}
          skip-tests: ${{ vars.SKIP_TESTS }}
          platform: linux/amd64
          platform-name: linux-amd64
          docker-push: false
          docker-image-name: ghcr.io/${{ github.repository }}
          docker-bake-meta-file-path: ${{ needs.setup.outputs.ezbookkeeping-docker-bake-meta-file-path }}
          docker-bake-meta-artifact-name: ${{ needs.setup.outputs.ezbookkeeping-docker-bake-meta-artifact-name }}
          docker-bake-digests-file-path: ${{ needs.setup.outputs.ezbookkeeping-docker-digests-file-path }}
          docker-bake-digests-artifact-name-prefix: ${{ needs.setup.outputs.ezbookkeeping-docker-digests-artifact-name-prefix }}
          package-file-name-prefix: ${{ needs.setup.outputs.ezbookkeeping-package-file-name-prefix }}
          package-artifact-name-prefix: ${{ needs.setup.outputs.ezbookkeeping-package-artifact-name-prefix }}
